
public class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
  ///MORA HETEROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  ///OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  ///OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  ///OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  ///OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  ///OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOm
	}

}
